"""create_recommendation_tables

Revision ID: 514756f0718c
Revises: 
Create Date: 2026-01-22 11:12:14.702812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514756f0718c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rec_context_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.Column('program_overview', sa.Text(), nullable=True),
    sa.Column('curriculum_highlights', sa.Text(), nullable=True),
    sa.Column('research_strengths', sa.Text(), nullable=True),
    sa.Column('faculty_quality_notes', sa.Text(), nullable=True),
    sa.Column('career_outcomes_summary', sa.Text(), nullable=True),
    sa.Column('industry_connections', sa.Text(), nullable=True),
    sa.Column('internship_support_notes', sa.Text(), nullable=True),
    sa.Column('alumni_presence_notes', sa.Text(), nullable=True),
    sa.Column('campus_life_overview', sa.Text(), nullable=True),
    sa.Column('city_lifestyle_notes', sa.Text(), nullable=True),
    sa.Column('cost_of_living_context', sa.Text(), nullable=True),
    sa.Column('part_time_work_context', sa.Text(), nullable=True),
    sa.Column('common_challenges', sa.Text(), nullable=True),
    sa.Column('who_should_avoid_this_program', sa.Text(), nullable=True),
    sa.Column('known_application_pitfalls', sa.Text(), nullable=True),
    sa.Column('context_tags', sa.JSON(), nullable=True),
    sa.Column('tone_hint', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rec_eligibility_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.Column('academic_score_band', sa.String(), nullable=True),
    sa.Column('language_score_band', sa.String(), nullable=True),
    sa.Column('background_match_level', sa.String(), nullable=True),
    sa.Column('minimum_degree_requirement', sa.String(), nullable=True),
    sa.Column('work_experience_preference', sa.String(), nullable=True),
    sa.Column('work_experience_years_band', sa.String(), nullable=True),
    sa.Column('gap_year_tolerance_level', sa.String(), nullable=True),
    sa.Column('academic_consistency_preference', sa.String(), nullable=True),
    sa.Column('research_experience_preference', sa.String(), nullable=True),
    sa.Column('historical_acceptance_strictness', sa.String(), nullable=True),
    sa.Column('borderline_profile_acceptance', sa.String(), nullable=True),
    sa.Column('competition_level_this_intake', sa.String(), nullable=True),
    sa.Column('eligibility_risk_level', sa.String(), nullable=True),
    sa.Column('key_risk_factors', sa.JSON(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('eligibility_confidence_level', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('eligibility_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rec_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('intake_term', sa.String(), nullable=True),
    sa.Column('intake_year', sa.Integer(), nullable=True),
    sa.Column('application_open_date', sa.Date(), nullable=True),
    sa.Column('application_close_date', sa.Date(), nullable=True),
    sa.Column('intake_status', sa.String(), nullable=True),
    sa.Column('seats_estimate_band', sa.String(), nullable=True),
    sa.Column('data_confidence_level', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rec_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('degree_type', sa.String(), nullable=True),
    sa.Column('program_domain', sa.String(), nullable=True),
    sa.Column('program_name', sa.String(), nullable=True),
    sa.Column('language_of_instruction', sa.String(), nullable=True),
    sa.Column('typical_duration_months', sa.Integer(), nullable=True),
    sa.Column('tuition_fee_band', sa.String(), nullable=True),
    sa.Column('program_orientation', sa.String(), nullable=True),
    sa.Column('delivery_mode', sa.String(), nullable=True),
    sa.Column('program_competitiveness_band', sa.String(), nullable=True),
    sa.Column('background_preference_tags', sa.JSON(), nullable=True),
    sa.Column('industry_alignment_tags', sa.JSON(), nullable=True),
    sa.Column('typical_class_size_band', sa.String(), nullable=True),
    sa.Column('internship_opportunities', sa.String(), nullable=True),
    sa.Column('career_outcomes_focus', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rec_universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('institution_type', sa.String(), nullable=True),
    sa.Column('global_reputation_band', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('university_category', sa.String(), nullable=True),
    sa.Column('campus_type', sa.String(), nullable=True),
    sa.Column('country_region', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rec_universities')
    op.drop_table('rec_programs')
    op.drop_table('rec_intakes')
    op.drop_table('rec_eligibility_snapshots')
    op.drop_table('rec_context_knowledge')
    # ### end Alembic commands ###
